### PR TITLE
Dsidirop/tasks/iban 00019 add support for exotic countries

### PR DESCRIPTION
**Pull request by dsidirop**
https://github.com/sinkien/IBAN4Net/issues/19

### CODE REVIEW

**Review by jpacchiarotti — APPROVED** [review]
I double checked with the BBAN definitions on the internet and it is ok, good job !

**Comment by dsidirop** [comment]
> I double checked with the BBAN definitions on the internet and it is ok, good job !

Cool! Thanks for tuning in. Feel free to copy-paste links to the resources that mention the specs. I had to hunt high and low to find the specs in various websites + wikipedia so if you have a resource which contains all specs for all ibans in a single place I would appreciate it!

**Comment by jpacchiarotti** [comment]
> > I double checked with the BBAN definitions on the internet and it is ok, good job !
> 
> Cool! Thanks for tuning in. Feel free to copy-paste links to the resources that mention the specs you checked the pull-request against. I'm saying this because I had to hunt "high and low" to find the specs in various websites + wikipedia so if you have a resource which contains all specs for all ibans in a single place I would very much appreciate it!
> 
> Thanks again and stay safe!

Hi, here is the place where I found the specs: https://en.wikipedia.org/wiki/International_Bank_Account_Number

**Comment by ShrujanKotturi** [comment]
Any issues with this PR, can we have this merged?

**Comment by jpacchiarotti** [comment]
Yeah sure, I see no problem merging this PR

**Comment by ShrujanKotturi** [comment]
Can someone approve this PR?

**Comment by pereddyvenkat** [comment]
I  cross checked with the BBAN definitions and it looks good. Thanks @ShrujanKotturi

**Comment by sinkien** [comment]
I love conflicting pulls...

**Pull request merged**
